### PR TITLE
Equals Sign Should Not be used in ChocolateBars Example

### PR DESCRIPTION
**Pull request by shreypdev**
## Description ⚡️ 🚀

When we have available small boxes exactly equals to the required small boxes. In this case, it shows that it **cannot** pack the bag, instead it should be able to pack.

## Link to test 🔗 👨🏼‍💻 

http://tpcg.io/ScvdWTbE

### CODE REVIEW

**Comment by mauricioaniche** [comment]
That's a great catch!! We find this bug in the next chapter!

I should definitely change that, as you are not the first one opening an issue for that!!

(In fact, it's already fixed in the private version I will release soon!)

**Comment by shreypdev** [comment]
@mauricioaniche Thanks for replying. I closed this one as I saw later that the correct answer is explained in next chapter.

But what I think that in this chapter you should show correct solution as I assumed that it should be correct and spend some time debugging and thinking that I might be taking it in a wrong way. In next chapter you can say by giving an example say if we add an equal to sign what can go wrong. This way it will be much more clear.

I hope your changes are similar to what I explained in you private version, If not I would be interested in looking what changes are made. So no need to reopen this right?

**Comment by mauricioaniche** [comment]
Thanks for the suggestion!

The new version has a completely new example for the specification-based testing chapter. Then, this chocolate problem appears fully in the boundary testing chapter. So, things are more contained now ! :)

**Comment by shreypdev** [comment]
Perfect @mauricioaniche you got it covered. 👍🏻

**Pull request closed without merging**
